# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yang Li
email: ddly22000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liyangnyc.com" # the base hostname & protocol for your site
timezone: America/New_York

# Modules
modules:
  -
    name: About
    permalink: /about
  -
    name: Posts
    permalink: /posts
  -
    name: Contact
    permalink: /contact

# Assets
icons_path: /assets/icons/

# Social Media
social_media:
  -
    name: twitter
    baseurl: https://twitter.com/
    username: ddly22000
  -
    name: github
    baseurl: https://github.com/
    username: ddly2
  -
    name: linkedin
    baseurl: https://linkedin.com/in/
    username: liyangnyc
  # -
  #   name: instagram
  #   baseurl: https://instagram.com/
  #   username: ddly2nyc

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: lynyc
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: lynyc

static_files:
  -
    linkedin:
      path: assets/linkedin
      modified_time: ""
      extname: png
